### ISSUE TITLE
[BUG]Execution failed for task ':photo_manager:compileDebugKotlin'.

### ISSUE THREAD

**Issue by ClarkChu07** [fluttercandies/flutter_photo_manager#846] opened 2022-10-13 09:51 UTC
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':photo_manager:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by ClarkChu07** [comment] 2022-10-13 10:00
solution：
`
1. flutter clean
2. flutter clean
3. flutter pub cache clean
4. flutter pub get
`

**Comment by AlexV525** [comment] 2022-10-13 11:08
Duplicate of #561

**Closed by AlexV525** 2022-10-13 11:08 UTC
