### ISSUE TITLE
[BUG] Edited video are not displayed correctly

### ISSUE THREAD

**Issue by Tom3652** [fluttercandies/flutter_photo_manager#685] opened 2022-01-19 11:05 UTC
**Describe the bug**

I am not sure that it's a ```Widget``` - related issue or the retrieved file itself, but displaying the content of ```assetEntity.file``` in the official example code of this plugin is showing a black rect on the screen if ```assetEntity.file``` is supposed to retrieve an edited video (iOS only, have not tested on Android).  

From a UI point of view, it seems that this ```rect``` has a width equal to the ```cropped``` region in the edited video.  
Hard to tell for the height since we don't see the real edited video content in the widget despite the ```BoxFit.fill``` or ```BoxFit.cover```.

**To Reproduce**
1. Edit a video (crop it in your iPhone's photo app)
2. Run the official example code
3. Show detail page of the edited video 
4. See the black screen

We can see this behavior using also ```assetEntity.getMediaUrl```.

**Expected behavior**
The edited video should be rendered as it is seen in the ```Photos``` native application on iOS.

**Screenshots**

https://user-images.githubusercontent.com/32631467/150109912-dcc72ee2-1e17-469b-bf9f-ae6cdb4914cb.MOV

**Flutter version**

**Smartphone (please complete the following information):**
 - Device: iPhone 8, iPhone XS Max, iPhone 12 Pro
 - OS: iOS 15.2.1, iOS 15.1.1

**Code**

In the ```initState``` of ```video_widget.dart``` you can play with this code and see the behavior with any of the chosen method :

```
@override
  void initState() {
    super.initState();
    /*
    widget.entity.file.then((File? file) {
      if (!mounted || file == null) {
        return;
      }
      _controller = VideoPlayerController.file(file)
        ..initialize()
        ..addListener(() => setState(() {}));
      setState(() {});
    });
     */
    
    widget.entity.getMediaUrl().then((String? url) {
      if (!mounted || url == null) {
        return;
      }
      _controller = VideoPlayerController.network(url)
        ..initialize()
        ..addListener(() => setState(() {}));
      setState(() {});
    });
  }
```

**Comment by AlexV525** [comment] 2022-01-19 11:33
You can also try to re-install your app.

**Comment by AlexV525** [comment] 2022-01-19 11:35
Unfortunately, I'm not able to reproduce this issue. Tested on iPhone 12, iOS 15.2.

https://user-images.githubusercontent.com/15884415/150122231-b6759abb-14f6-44c2-944e-4ee607ea9f34.mp4

**Comment by Tom3652** [comment] 2022-01-19 13:08
> You can also try to uninstall && re-install your app, in order to clear caches.

I have done it (clearing the cache) before creating the issue and it didn't change it :/ 

Here is my output with the latest code : 

https://user-images.githubusercontent.com/32631467/150135406-2059e5b9-5d0b-491b-989f-c680db3f7fd2.mp4

Is your above code using ```assetEntity.file``` ? And do you have the same output using ```getMediaUrl``` ?  

I have read your last commit, but i just don't understand anything in Obj-C langage 😅

**Comment by AlexV525** [comment] 2022-01-19 13:39
> Is your above code using `assetEntity.file` ? And do you have the same output using `getMediaUrl` ?

I'm using the `file` getter, `getMediaUrl` requires `isLocallyAvailable`, the example didn't toggle the same mechanism.

Which device you're testing and which version of iOS? Is it iPhone 8?

**Comment by Tom3652** [comment] 2022-01-19 14:01
The video was recorded with iPhone 8 under iOS 15.2.1.  

The same output is given when tested on iPhone 7+ under iOS 14.7.1 and on my iPhone 12 pro max under iOS 15.1.1

**Comment by AlexV525** [comment] 2022-01-19 14:15
Can you make a screenrecord using 12?

**Comment by Tom3652** [comment] 2022-01-19 15:39
Yes sure (you will even hear the sound showing that it's playing) : 
 
https://user-images.githubusercontent.com/32631467/150162482-4c0aeb67-c03a-452f-ae9d-d84a914408ee.mp4

I have cropped "too much" so there is a black screen > phone's width 😅

**Comment by AlexV525** [comment] 2022-01-19 16:27
Where did your photos come from? It's too weird that we're using almost the same device but I can't reproduce this as my comment above.

**Comment by Tom3652** [comment] 2022-01-19 16:34
Yes you were right, this is due to the landscape and I was taking videos from the native iOS camera app.   
If i crop in an aspect ratio that is smaller than the device it's working :)  
Can you confirm that by doing the opposite on your side ?  Cropping a video with a big enough portrait aspect ratio (> 2)

**Comment by AlexV525** [comment] 2022-01-19 16:38
> If i crop in an aspect ratio that is smaller than the device it's working :)

I don't have dev env near me, but if you're available, you can try with the example of the video_player. Now I'm pretty sure it's related to the player, not the manager.

**Comment by Tom3652** [comment] 2022-01-19 19:32
Thanks for specifications, yes i will try then and make some tests with the ```video_player``` using ```image_picker``` for example.

**Comment by AlexV525** [comment] 2022-01-20 03:55
Related to flutter/flutter#70261, flutter/plugins#1307.

**Comment by Tom3652** [comment] 2022-01-20 11:44
I confirm that this also happens with ```image_picker``` so i will make a new issue in the flutter repo regarding these specifications because there doesn't seem to be any rotation involved here...

I have also noticed that if you trim the video, save it, then crop it and save it again with any aspect ratio, it works fine...

**Comment by Tom3652** [comment] 2022-01-20 14:40
I confirm that it's because of [flutter/flutter#71299](https://github.com/flutter/flutter/issues/71299) and i have made the provided fix there in my app that is also working !

**Comment by AlexV525** [comment] 2022-01-20 14:47
Closing as it's confirmed out of support. I'll try with that fix see if it's easy to apply and add tests.

**Comment by Tom3652** [comment] 2022-01-20 14:49
This [comment](https://github.com/flutter/flutter/issues/71299#issuecomment-878506319) reflects the PR you pointed out and fixes it.

**Comment by AlexV525** [comment] 2022-01-20 14:57
Sure, the point is to write tests.

**Closed** 2022-01-20 14:56 UTC
Labels: Sort: BUG, Platform: iOS, Type: Video, Sort: Out of support, Status: Need investigate

**Comment by AlexV525** [comment] 2022-03-23 02:11
@Tom3652 Can you verify the video playing by overriding the `video_player` to flutter/plugins@5483df7 to see if the above cases play normally?

**Comment by Tom3652** [comment] 2022-03-23 08:45
Hi @AlexV525 yes sure, but the link you provided seems broken i can't open it :/

**Comment by AlexV525** [comment] 2022-03-23 08:47
```yaml
dependency_overrides:
  video_player_avfoundation:
    git:
      url: https://github.com/AlexV525/flutter-plugins
      path: packages/video_player/video_player_avfoundation
      ref: '5483df7'
```

**Comment by Tom3652** [comment] 2022-03-23 12:09
You did an amazing rework here ! 
It works perfectly with the edited videos with any kind of aspect ratio (> 1 or <= 1) :)

Besides, my videos from whatsapp are now displayed on iOS, before it was a full black screen and only audio was playing.

**Comment by AlexV525** [comment] 2022-03-23 12:54
> It works perfectly with the edited videos with any kind of aspect ratio (> 1 or <= 1) :)

Thanks for the feedback. 👍

**Comment by Tom3652** [comment] 2022-05-12 13:34
Hi @AlexV525 and thanks for your work in the `video_player`. 
The PR was merged, but i didn't see it mentioned in video_player's changelog.  
Do you know if i can remove your github `video_player_avfoundation` from my `pubspec.yml` or should i keep waiting ?

Thanks again !

**Comment by AlexV525** [comment] 2022-05-12 13:46
> Do you know if i can remove your github `video_player_avfoundation` from my `pubspec.yml` or should i keep waiting ?

Please remove the override and run `flutter pub upgrade`, then make sure the `video_player_avfoundation`s version is above `2.3.2` by checking the `pubspec.lock`.

**Comment by Tom3652** [comment] 2022-05-12 13:54
Alright i have the `2.3.4`, thanks 👌🏼
