### ISSUE TITLE
Type 'DecoderCallback' not found

### ISSUE THREAD

**Issue by wozyao** [fluttercandies/flutter_photo_manager#1036] opened 2023-11-16 02:54 UTC
### Version

2.8.1

### Platforms

Android, iOS

### Device Model

iPhone 15 Pro(iOS 17.1.1)

### flutter info

```sh
../../.pub-cache/hosted/pub.flutter-io.cn/photo_manager-2.8.1/lib/src/internal/image_provider.dart:71:5: Error: Type 'DecoderCallback' not found.
```

### How to reproduce?

![WX20231116-105356@2x](https://github.com/fluttercandies/flutter_photo_manager/assets/15340066/0a6640fa-5eb7-41d2-b292-6561754a78a5)

### Logs

```sh
../../.pub-cache/hosted/pub.flutter-io.cn/photo_manager-2.8.1/lib/src/internal/image_provider.dart:71:5: Error: Type 'DecoderCallback' not found.
```

**Comment by AlexV525** [comment] 2023-11-16 02:55
Duplicate of #1021

**Closed** 2023-11-16 02:54 UTC
Labels: await triage

**Comment by xacaciax** [comment] 2023-11-17 23:51
Same issue here
