### ISSUE TITLE
Error when building ipa

### ISSUE THREAD

**Issue by Weav3r** [fluttercandies/flutter_photo_manager#1044] opened 2023-11-22 16:08 UTC
### Version

2.8.1

### Platforms

iOS

### Device Model

iPhone 14

### flutter info

```sh
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on macOS 13.6.1 22G313 darwin-x64, locale en-GB)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      flutter config --android-sdk to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Connected device (2 available)
[✓] Network resources
```

### How to reproduce?

Can't provide reproducible steps

### Logs

```sh
Error (Xcode): ../.pub-cache/hosted/pub.dev/photo_manager-2.8.1/lib/src/internal/image_provider.dart:71:5: Error:
Type 'DecoderCallback' not found.


Encountered error while archiving for device.
```

**Comment by AlexV525** [comment] 2023-11-23 01:40
Duplicate of #1021

**Closed by AlexV525** 2023-11-23 01:40 UTC
Labels: await triage
