### ISSUE TITLE
[BUG] PMProgressHandler not emitting events and called even for non iCloud files

### ISSUE THREAD

**Issue by Tom3652** [fluttercandies/flutter_photo_manager#679] opened 2022-01-08 16:25 UTC
**Describe the bug**

I am fetching videos and, as you have taken the time to explain me in #661, the ```AssetEntity.file``` or ```.originFile``` can take time to be retrieved on iOS because is not ```locallyAvailable``` and needs to be fetched from iCloud. 

I have 2 issues with this : 

- First problem : ```assetEntity.file``` or any other method is sometimes fetching the file but i have iCloud disabled on my iPhone and never put any files there, tested on 3 different iPhones without iCloud and all have the download but not all files. 

- Second problem : In ```photo_manager: ^1.3.10```, i had the progress as below : 

```
File? tempFile;
      if (assetEntity.type == AssetType.video) {
        PMProgressHandler handler = PMProgressHandler();
        StreamSubscription subscription = handler.stream.listen((event) {
          if (kDebugMode) {
            LogManager.w("Event : ${event.state}, progress : ${event.progress} & time : ${DateTime.now().second}");
          }
        });
        tempFile = await assetEntity.loadFile(isOrigin: false, progressHandler: handler);
        subscription.cancel();
      }
      else {
        tempFile = await assetEntity.loadFile(isOrigin: false);
      }
```
But in ```2.0.0-dev.2```, i have no events emitted except this one from the above log : 

```
flutter: Event : PMRequestState.prepare, progress : 0.0 & time : 20
```
And the file is ready 5-10 seconds later.  
I am aware that ```2.0.0``` is still under development of course or maybe it's something i am doing wrong with the methods to fetch files.

**To Reproduce**
1. Filter your gallery with :  ```final albums = await PhotoManager.getAssetPathList(onlyAll: true, type: RequestType.video)```
2. Attach the above code as listener
3. Check if you have not iCloud if some files are anyway downloading 
4. See that no progress is emitted but the load takes few seconds

**Expected behavior**

- The file to not be downloaded when iCloud is disabled on the iPhone (in my case i have never put anything in iCloud so it's not even a user who has disabled iCloud after putting some videos there)
- If the file needs to be downloaded (truly) from iCloud, then emit the progress in the ```PMProgressHandler``` as it was done in ```1.3.10``` please

**Flutter version**

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale fr-FR)
    • Flutter version 2.8.1 at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Users/foxtom/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • Now You See Me (mobile) • 00008020-001204401E78002E • ios            • iOS 15.2 19C56
    • macOS (desktop)         • macos                     • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 97.0.4692.71

• No issues found!
```

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max, iPhone 12, iPhone 13 pro max
 - OS: iOS 14+ - iOS 15+

**Comment by AlexV525** [comment] 2022-01-10 03:25
> First problem : assetEntity.file or any other method is sometimes fetching the file but i have iCloud disabled on my iPhone and never put any files there, tested on 3 different iPhones without iCloud and all have the download but not all files.

This is out of support. We cannot control how a file behaves or where it's been stored.

**Comment by AlexV525** [comment] 2022-01-10 03:50
Can you use `git bisect` to check commits between `1.3.10` and `2.0.0`? I don't have much time since we're at the end of the lunar year and have massive work to deal with.

More specifically, `git bisect start 947cf50 1dad659`.

**Comment by AlexV525** [comment] 2022-01-10 10:06
> Same using `image_picker` actually it doesn't download.

That's why we have `AssetEntity`, and once you start to retrieve the `file`, it should be fetched.

**Comment by Tom3652** [comment] 2022-01-10 10:24
I understand, but when i use ``` XFile? file = await picker.pickVideo(source: ImageSource.gallery);``` and then click on the ```play``` button, it's instantly playing the video and is not fetched. 

The same video picked above is fetched during few seconds using ```assetEntity.file``` once the first time.  
But after the first time it's always fluent and working very fine yes. 
 
I simply don't want my iOS users to see for the first time in their life ```downloading asset...``` in my UI when the same file is available directly in other apps...  Especially if they don't use iCloud. 
I will try to find some time to take a look at the code and understand better the Swift API, i am not saying that there is a bug here but since the behavior is different in other apps it simply makes me wonder if there is another way to do so. 90% of my iOS beta testers complained about it :/

**Comment by AlexV525** [comment] 2022-01-10 10:28
Please file separate issues to track different things.

**Comment by AlexV525** [comment] 2022-01-17 05:13
I didn't reproduce this issue either with iCloud or non-iCloud files.

Files with iCloud:

```
2022-01-17 13:11:15.271918+0800 Runner[17598:6803905] PhotoManager info: cache path = /private/var/mobile/Containers/Data/Application/83E1B5F6-2133-4E16-8895-453A27C3A3F7/tmp/.image
2022-01-17 13:11:15.280449+0800 Runner[17598:6803079] flutter: progress state onChange: PMRequestState.prepare, progress: 0.0
2022-01-17 13:11:16.082437+0800 Runner[17598:6803079] flutter: progress state onChange: PMRequestState.loading, progress: 0.97
2022-01-17 13:11:16.104184+0800 Runner[17598:6803079] flutter: progress state onChange: PMRequestState.loading, progress: 0.99
2022-01-17 13:11:16.134308+0800 Runner[17598:6803079] flutter: file = File: '/private/var/mobile/Containers/Data/Application/83E1B5F6-2133-4E16-8895-453A27C3A3F7/tmp/.image/(null)'
2022-01-17 13:11:16.134564+0800 Runner[17598:6803079] flutter: progress state onChange: PMRequestState.success, progress: 1.0
```

Files that already locally available:
```
2022-01-17 13:12:00.283762+0800 Runner[17598:6804273] PhotoManager info: cache path = /private/var/mobile/Containers/Data/Application/83E1B5F6-2133-4E16-8895-453A27C3A3F7/tmp/.image
2022-01-17 13:12:00.284935+0800 Runner[17598:6803079] flutter: progress state onChange: PMRequestState.prepare, progress: 0.0
2022-01-17 13:12:00.289065+0800 Runner[17598:6803079] flutter: progress state onChange: PMRequestState.success, progress: 1.0
2022-01-17 13:12:00.289318+0800 Runner[17598:6803079] flutter: file = File: '/private/var/mobile/Containers/Data/Application/83E1B5F6-2133-4E16-8895-453A27C3A3F7/tmp/.image/IMG_0215.JPG'
```

**Comment by Tom3652** [comment] 2022-01-17 14:29
Thanks a lot for your time.  
I saw that you are using ```getMediaUrl``` on the ```AssetEntity```, and it gives the expected UI behavior, instantly played when not from iCloud and with edited changes ! :).  
This actually solve #678 in UI perspective.

However, it's doesn't seem possible to upload it (my goal is to upload it like on any app afterwards) because this ```mediaUrl``` is not a File / bytes (```File(mediaUrl).existsSync()``` returns false).

If i get the ```assetEntity.file``` right before upload (and use ```getMediaUrl``` for the preview only), i will not upload the edited file but the original one, even if i use ```loadFile(isOrigin: false)```.  

Do you know how can we actually use this ```mediaUrl``` to upload the file please ?

**Comment by AlexV525** [comment] 2022-01-17 15:06
I'm not sure how you combine these issues together. In #678 you're indicating an editing issue rather than the loading one.

`getMediaUrl` returns the `ContentURI` and the file URL of `AVAsset` which is playable from the native, as documented:
https://github.com/fluttercandies/flutter_photo_manager/blob/48dd4af7e100463c2ecbc09d3302c738662fd6be/lib/src/types/entity.dart#L593-L597
It's not related to whether the resource is ready for I/O usage.

If you don't have further issues with `PMProgressHandler`, please close this issue. Otherwise, let's focus on one perspective at a time.

**Comment by AlexV525** [comment] 2022-01-18 03:31
Still unable to reproduce the issue. Closing as it's not reproducible.

| iCloud file | non-iCloud file |
| :------: | :------: |
| ![image](https://user-images.githubusercontent.com/15884415/149866004-6d71a9e8-914f-4297-ad04-9c5001bf4feb.png) | ![image](https://user-images.githubusercontent.com/15884415/149866091-5ac6826b-786a-48fd-b22f-94709f468c49.png) |

**Closed by AlexV525** 2022-01-18 03:31 UTC
Labels: Sort: BUG, Status: More info or use case, Platform: iOS, Type: Photo library

**Comment by AlexV525** [comment] 2024-08-07 19:03
Fixed by https://github.com/fluttercandies/flutter_photo_manager/pull/1174
