### ISSUE TITLE
[BUG] App crashed when getting images

### ISSUE THREAD

**Issue by bilalraad** [fluttercandies/flutter_photo_manager#811] opened 2022-08-07 07:29 UTC
Hello,
I'm using [advance_image_picker](https://pub.dev/packages/advance_image_picker) in my app and I'm facing a problem when I'm trying to select images from the gallery. The app crashes as soon as the user clicks the "select" button on the Samsung device. 

![Screenshot_1659856949](https://user-images.githubusercontent.com/49819546/183280154-54a5a083-375a-47d2-bc55-e443f62b3e5b.png)

difficult to reproduce

**Flutter version**
3.0.5

**Smartphone (please complete the following information):**
 - Device: Samsung s8+
 - OS: Android 9

These are the logs from firebase crashlytics 

```bash
com.fluttercandies.photo_manager.core.utils.IDBUtils$DefaultImpls.getString (IDBUtils.kt:138)
com.fluttercandies.photo_manager.core.utils.DBUtils.getString (DBUtils.kt:22)
com.fluttercandies.photo_manager.core.utils.IDBUtils$DefaultImpls.toAssetEntity (IDBUtils.kt:176)
com.fluttercandies.photo_manager.core.utils.DBUtils.toAssetEntity (DBUtils.kt:22)
com.fluttercandies.photo_manager.core.utils.DBUtils.getAssetListRange (DBUtils.kt:216)
com.fluttercandies.photo_manager.core.PhotoManager.getAssetListRange (PhotoManager.kt:81)
com.fluttercandies.photo_manager.core.PhotoManagerPlugin$onHandlePermissionResult$3.invoke (PhotoManagerPlugin.kt:266)
com.fluttercandies.photo_manager.core.PhotoManagerPlugin$onHandlePermissionResult$3.invoke (PhotoManagerPlugin.kt:259)
com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion.runOnBackground$lambda-0 (PhotoManagerPlugin.kt:46)
com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion.lambda$bZa62ZrXsGssc32bPH4oVAuIci4
com.fluttercandies.photo_manager.core.-$$Lambda$PhotoManagerPlugin$Companion$bZa62ZrXsGssc32bPH4oVAuIci4.run (Unknown Source:2)
```

**Comment by AlexV525** [comment] 2022-08-07 07:34
Duplicate of #809.

**Closed by AlexV525** 2022-08-07 07:34 UTC
