### ISSUE TITLE
[BUG] PhotoManager.getAssetPathList return empty list in some Android devices

### ISSUE THREAD

**Issue by vantutrieu97** [fluttercandies/flutter_photo_manager#890] opened 2023-01-09 07:16 UTC
**Describe the bug**
I have 6 devices to test, 2 iOS and 4 Android. All of iOS devices is working very good but 2 of 4 Android device can not get asset path list (always return list empty, I sure I can see a lot of image I was taken when I open Gallery app of device)
Please help me

**To Reproduce**
```bash
1. Request permission
2. Call getAssetPathList method and return empty list
```

**Smartphone (please complete the following information):**
```
1.
 - Device: [Pixel 6]
 - OS: [Android 13]
2.
 - Device: [Samsung M22]
 - OS: [Android 13 (One UI 5.0)]
```
**Flutter version**
```bash
[✓] Flutter (Channel stable, 3.0.5, on macOS 13.1 22C65 darwin-arm, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2022.2.3)
[✓] VS Code (version 1.73.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```

**Screenshots**
![Screenshot 2023-01-09 at 14 13 28](https://user-images.githubusercontent.com/23252827/211256828-959af3c1-ae8f-4f38-9da8-8002e99c49df.png)

**Comment by vantutrieu97** [comment] 2023-01-09 09:54
@AlexV525  can you help me? This error only occurs on some devices :(

**Comment by vantutrieu97** [comment] 2023-01-09 10:18
Android 11, 12 woking @AlexV525

**Comment by pham-k** [comment] 2023-01-10 02:17
I also have the same problem.

**Comment by AlexV525** [comment] 2023-01-10 06:56
Duplicate of #852

**Closed by AlexV525** 2023-01-10 06:56 UTC
Labels: Sort: Invalid, Invalid: Missing requirements
