### ISSUE TITLE
[BUG] Unresolved reference: lowercase

### ISSUE THREAD

**Issue by bugrevealingbme** [fluttercandies/flutter_photo_manager#813] opened 2022-08-14 10:17 UTC
Flutter 3.0.5

flutter/.pub-cache/hosted/pub.dartlang.org/photo_manager-2.2.0/android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/ConvertUtils.kt: (59, 29): Unresolved reference: lowercase

**Comment by AlexV525** [comment] 2022-08-14 11:49
Duplicate of #561

**Closed** 2022-08-14 11:50 UTC
