### ISSUE TITLE
[Bug report] 

### ISSUE THREAD

**Issue by jsshizhan** [fluttercandies/flutter_photo_manager#978] opened 2023-08-24 07:52 UTC
### Version

2.7.1

### Platforms

Android

### Device Model

android 11

### flutter info

```sh
[√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [版本 10.0.19044.3086], locale zh-CN)
    • Flutter version 3.0.2 at C:\Users\User\fvm\default
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (1 year, 3 months ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at F:\android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.5)
    • Visual Studio at F:\Program Files (x86)\Microsoft Visual Studio\2019
    • Visual Studio Community 2019 version 16.11.31729.503
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Dart plugin version 231.9065

[√] Connected device (4 available)
    • V1824A (mobile)   • emulator-5554 • android-x64    • Android 7.1.2 (API 25)
    • Windows (desktop) • windows       • windows-x64    • Microsoft Windows [版本 10.0.19044.3086]
    • Chrome (web)      • chrome        • web-javascript • Google Chrome 115.0.5790.171
    • Edge (web)        • edge          • web-javascript • Microsoft Edge 111.0.1661.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

### How to reproduce?

flutter build apk

why remove package from AndroidManifest.xml?

### Logs

```sh
Execution failed for task ':photo_manager:processReleaseManifest'.
> Error while evaluating property 'packageOverride' of task ':photo_manager:processReleaseManifest'
   > Failed to calculate the value of task ':photo_manager:processReleaseManifest' property 'packageOverride'.
      > Failed to query the value of property 'applicationId'.
         > Package Name not found in /root/.pub-cache/hosted/pub.dartlang.org/photo_manager-2.7.1/android/src/main/AndroidManifest.xml
```

**Comment by AlexV525** [comment] 2023-08-24 10:10
Duplicate of #968

**Closed** 2023-08-24 10:10 UTC
