### ISSUE TITLE
[BUG] [Editor.iOS] favoriteAsset is not marking the asset as favorite

### ISSUE THREAD

**Issue by ua741** [fluttercandies/flutter_photo_manager#746] opened 2022-04-03 10:18 UTC
**Describe the bug**

In IOS, when we try to mark an asset as favorite, the change is not reflected in the native Photos library. 
 `await PhotoManager.editor.iOS.favoriteAsset(entity: entity, favorite: true|false);`

**To Reproduce**

In the example app: 

1. Add build Info item about favorite flag in `CommonUtil.showInfoDialog` 
```
GestureDetector(
                child: _buildInfoItem('isFavorite', entity.isFavorite.toString()),
                onLongPress: () async {
                  final bool isCurrentlyFavorite = entity.isFavorite;
                  final AssetEntity? resultAssetEntity =  await PhotoManager.editor.iOS.favoriteAsset(entity: entity, favorite: !isCurrentlyFavorite);
                  final AssetEntity? actualAssetEntity = await AssetEntity.fromId(entity.id);
                  if (actualAssetEntity == null || resultAssetEntity == null) {
                    showToast('resultAssetEntity is null: ${resultAssetEntity != null} \n'
                        'actualAssetEntity is null: ${actualAssetEntity != null}');
                  } else {
                    if (isCurrentlyFavorite) {
                      showToast('mark un-favorite. \nresultEntity = ${resultAssetEntity.isFavorite} \nactualEntity = ${actualAssetEntity.isFavorite}');
                    } else {
                      showToast('mark favorite. \nresultEntity = ${resultAssetEntity.isFavorite} \nactualEntity = ${actualAssetEntity.isFavorite}');
                    }
                  }
                },
              ),
```

2. Long press on favorite build info item to toggle favorite state.

**Expected behavior**
- The favorite flag state for the local state should be changed in the native Photos app.

**Flutter version**
- Flutter version 2.8.1

**Smartphone (please complete the following information):**
 - Device: Simulator: iOS 11 Pro
 - OS: iOS 14.5

**Comment by AlexV525** [comment] 2022-04-22 06:47
So what result returned eventually? Whether a null result or an unfavorited entity?

**Comment by ua741** [comment] 2022-04-22 07:53
> So what result returned eventually? Whether a null result or an unfavorited entity?
So the returned entity is non-null and result.isFavorite is set to whatever value we pass inside `editor.iOS>favoriteAsset()` method. But if we fetch the entity again using `AssetEntity.fromId(entity.id)`, we can verify that the favorite flag wasn't changed.

**Comment by ua741** [comment] 2022-04-22 07:53
> > So what result returned eventually? Whether a null result or an unfavorited entity?

So the returned entity is non-null and `result.isFavorite` is set to whatever value we pass inside `editor.iOS>favoriteAsset()` method. But if we fetch the entity again using `AssetEntity.fromId(entity.id)`, we can verify that the favorite flag wasn't changed.

**Comment by AlexV525** [comment] 2022-04-22 07:55
> But if we fetch the entity again using `AssetEntity.fromId(entity.id)`, we can verify that the favorite flag wasn't changed.

Can you determine whether the ID has been updated since the favorite action? Just in case.

**Comment by ua741** [comment] 2022-04-22 07:59
> > But if we fetch the entity again using `AssetEntity.fromId(entity.id)`, we can verify that the favorite flag wasn't changed.
> 
> Can you determine whether the ID has been updated since the favorite action? Just in case.

Can you please guide me on how can I check this?  In my Simulator, I tested with just two photos. After trying to edit the favorite flag, I was able to fetch the AssetEntity using the same ID. Have attached a video in the previous comment for reference.

**Comment by AlexV525** [comment] 2022-04-22 08:32
> Edit: Verified that the ID is not getting updated.

Thanks. I guess the issue is related to the access level with permissions. I don't have macOS development env nearby recently. Will check the issue in the next week.

**Comment by AlexV525** [comment] 2022-04-26 06:48
Weird. The change request reports succeed and no errors, but the `PHAsset.favorite` is still the same value.

**Comment by AlexV525** [comment] 2022-04-26 07:18
This could be related to the answer: https://stackoverflow.com/a/34689317/17742614

But after a long duration, the field doesn't seem to be changed at all.

**Comment by ua741** [comment] 2022-04-26 14:53
Yeah, it does look a little weird. Even on Apple's documentation, they have this [code sample](https://developer.apple.com/documentation/photokit/phassetchangerequest?language=objc)

```lang=objective-c
(void)toggleFavoriteForAsset:(PHAsset *)asset {
    [[PHPhotoLibrary sharedPhotoLibrary] performChanges:^{
        // Create a change request from the asset to be modified.
        PHAssetChangeRequest *request = [PHAssetChangeRequest changeRequestForAsset:asset];
        // Set a property of the request to change the asset itself.
        request.favorite = !asset.favorite;
    } completionHandler:^(BOOL success, NSError *error) {
        NSLog(@"Finished updating asset. %@", (success ? @"Success." : error));
    }];
}
```

Whatever examples I could find on the internet, all of them are using a similar code. 

--
I found this on the [discussion section](https://developer.apple.com/documentation/photokit/phassetchangerequest/1624050-changerequestforasset#discussion) for `changeRequestForAsset`, which might be relevant to this issue..

> Before editing an asset, use its [canPerformEditOperation:](https://developer.apple.com/documentation/photokit/phasset/1624779-canperformeditoperation) method to see if the asset allows editing.
> 
> After you create a change request within a photo library change block, propose changes to the original asset’s properties by setting the corresponding properties of the change request. After Photos runs your change block, the asset’s properties reflect your changes. For details on change blocks, see [PHPhotoLibrary](https://developer.apple.com/documentation/photokit/phphotolibrary).
> 
> To edit an asset’s image or video content, first begin a content editing session with the asset’s [requestContentEditingInputWithOptions:completionHandler:](https://developer.apple.com/documentation/photokit/phasset/1624061-requestcontenteditinginputwithop) method. You commit a content edit by setting the contentEditingOutput property of a change request within a change block. For more information about asset content editing, see [PHAsset](https://developer.apple.com/documentation/photokit/phasset).

**Comment by AlexV525** [comment] 2022-06-22 00:31
I've submitted a PR to use `canPerformEditOperation` before performing the change, though we can't do more things if it doesn't help since it's out of scope.

**Comment by AlexV525** [comment] 2022-07-07 09:12
Applying a valid fix from @CaiJingLong.

**Comment by AlexV525** [comment] 2022-07-07 18:26
To clarify what happened at the end:
The plugin fetches the entity every time, but once it's stored in the cache container, it won't get updates from regular obtain. In the PR the cache container is ignored when fetching the new entity properties.

**Closed** 2022-07-07 18:30 UTC
Labels: Sort: BUG, Platform: iOS, Type: Photo library, Status: Have use case, Type: Cache
