### ISSUE TITLE
Activity for the permission request is not exist.

### ISSUE THREAD

**Issue by ArZargaryan** [fluttercandies/flutter_photo_manager#830] opened 2022-09-19 15:46 UTC
The error.
```
E/flutter (15003): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Activity for the permission request is not exist., null, java.lang.NullPointerException: Activity for the permission request is not exist.
E/flutter (15003): 	at com.fluttercandies.photo_manager.permission.PermissionsUtils.getPermissionsWithTips(PermissionsUtils.kt:85)
E/flutter (15003): 	at com.fluttercandies.photo_manager.permission.PermissionsUtils.getPermissions(PermissionsUtils.kt:69)
E/flutter (15003): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin.onMethodCall(PhotoManagerPlugin.kt:209)
E/flutter (15003): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:261)
E/flutter (15003): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (15003): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:321)
E/flutter (15003): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$2j2MERcK825A5j1fv5sZ7xB2Iuo.run(Unknown Source:12)
E/flutter (15003): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (15003): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (15003): 	at android.os.Looper.loopOnce(Looper.java:233)
E/flutter (15003): 	at android.os.Looper.loop(Looper.java:344)
E/flutter (15003): 	at android.app.ActivityThread.main(ActivityThread.java:8191)
E/flutter (15003): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (15003): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/flutter (15003): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
E/flutter (15003): )
E/flutter (15003): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter (15003): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
E/flutter (15003): <asynchronous suspension>
E/flutter (15003): #2      PhotoManagerPlugin.requestPermissionExtend (package:photo_manager/src/internal/plugin.dart:72:24)
E/flutter (15003): <asynchronous suspension>
E/flutter (15003): #3      flutterIsolateFunction (package:stack/pages/post_creation/post_creation_page.dart:36:15)
E/flutter (15003): <asynchronous suspension>
E/flutter (15003): 
```

I'm trying to use this plugin in isolation, so i call the method below in isolation thanks to package FlutterIsolate(it gives you an ability to use flutter plugins in isolates).
```
@pragma('vm:entry-point')
void flutterIsolateFunction(List<int> args) async {
  final _ps = await PhotoManager.requestPermissionExtend();

  if (_ps.isAuth) {
    final paths = await PhotoManager.getAssetPathList();
    final recentPath = paths.firstWhereOrNull((el) => el.name.toLowerCase().contains("recent"));

    final assetPathEntity = recentPath ?? paths.first;

    print("HERE IS ASSET THE ASSET PATH ENTITY $assetPathEntity");
  } else {
    print("isAuth -> false");
  }
}
```
But it throws the error.
I tryed to use another plugin and that worked, but for photo_manager it still throws an error. I tryed many variations, but to no avil.

**Comment by AlexV525** [comment] 2022-09-19 16:49
The exception tells everything, that in this isolate environment the plugin is not registered properly. More specifically, not with the `ActivityAware`. The permission must be asked with a valid `Activity`. Duplicate of #591 #581.
Closing as resolved.

**Closed by AlexV525** 2022-09-19 16:49 UTC
