### ISSUE TITLE
[Bug report] 

### ISSUE THREAD

**Issue by OnTheTrackGO** [fluttercandies/flutter_photo_manager#941] opened 2023-07-04 08:23 UTC
### Version

2.6.0

### Platforms

Android

### Device Model

All device has android api 33

### flutter info

```sh
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.4.1 22F82 darwin-x64, locale en-VN)
    • Flutter version 3.3.10 on channel stable at /Volumes/SourceCode/Flutter_SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (7 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/onracings/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (Temurin)(build 1.8.0_302-b08)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS 13.4.1 22F82 darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 114.0.5735.198

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

### How to reproduce?

The issue always happen in android api 33

final paths =
        await PhotoManager.getAssetListPaged(page: _page, pageCount: _pageSize);

paths is empty

### Example code (optional)

```Dart
final paths =
        await PhotoManager.getAssetListPaged(page: 1, pageCount: 10);
```

### Contact

onthetrack.go@gmail.com

**Comment by AlexV525** [comment] 2023-07-04 09:39
Duplicate of #852

**Closed by AlexV525** 2023-07-04 09:39 UTC
