### ISSUE TITLE
[Question] How to find the corresponding file to a file receive by sharing

### ISSUE THREAD

**Issue by starshipcoder** [fluttercandies/flutter_photo_manager#817] opened 2022-08-25 11:55 UTC
I am using https://github.com/ShoutSocial/share_handler/tree/main/share_handler so a user can share a photo/video to my app. I get a SharedMediaFile object, this contains the file which is outside the device gallery.

How could I find (if exists) the corresponding file and its AssetEntity in the device gallery ?

Many thanks

**Comment by AlexV525** [comment] 2022-08-29 12:04
Duplicate of #795

**Closed by AlexV525** 2022-08-29 12:04 UTC

**Comment by starshipcoder** [comment] 2022-08-29 13:23
Not exactly the same question, I don't want to convert the receiving file into a AssetEntity but to find the corresponding file in the gallery
