### ISSUE TITLE
[Bug report] The plugin is incompatible with latest Flutter stable version 3.16

### ISSUE THREAD

**Issue by BazinC** [fluttercandies/flutter_photo_manager#1049] opened 2023-11-28 16:00 UTC
### Version

2.8.1 or lower

### Platforms

dart, Android, iOS, macOS

### Device Model

Any

### flutter info

```sh
[✓] Flutter (Channel stable, 3.16.1, on macOS 13.6 22G120 darwin-arm64, locale en-FR)
    • Flutter version 3.16.1 on channel stable at /Users/corentinbazin/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7f20e5d18c (22 hours ago), 2023-11-27 09:47:30 -0800
    • Engine revision 22b600f240
    • Dart version 3.2.1
    • DevTools version 2.28.3

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/corentinbazin/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /usr/bin/java
    ✗ Could not determine java version

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.84.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.77.20231101

[✓] Connected device (5 available)
    • Corentin’s iPhone 13 (mobile) • 00008110-001229512698401E            • ios            • iOS 17.0.3 21A360
    • iPad de Corentin (mobile)     • 00008103-001D71DA1E23001E            • ios            • iOS 17.0.2 21A351
    • iPhone 15 (mobile)            • 3BCA922A-8FAB-40BF-96E9-627C5200EDB9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)               • macos                                • darwin-arm64   • macOS 13.6 22G120 darwin-arm64
    • Chrome (web)                  • chrome                               • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.
```

### How to reproduce?

Build the any app using photo_manager with Flutter version 3.16.1

### Logs

```sh
Failed to build iOS app
Error (Xcode): ../../../../../.pub-cache/hosted/pub.dev/photo_manager-2.8.1/lib/src/internal/image_provider.dart:71:5: Error: Type 'DecoderCallback' not found.
image_provider.dart:71
Could not build the application for the simulator.
```

**Comment by BazinC** [comment] 2023-11-28 16:03
I know Flutter introduced internal breaking change, but I would like to know when you will fix this incompatibility because it's blocking us from upgrading flutter.
Thank you

**Comment by AlexV525** [comment] 2023-11-28 16:03
Duplicate of #1021

**Closed by AlexV525** 2023-11-28 16:03 UTC
Labels: await triage

**Comment by BazinC** [comment] 2023-11-28 16:04
Oh I missed that one, thank you ! :)
