### ISSUE TITLE
[Bug report] photo_manager

### ISSUE THREAD

**Issue by RexKim84** [fluttercandies/flutter_photo_manager#1043] opened 2023-11-21 14:39 UTC
### Version

2.8.1

### Platforms

dart, Android

### Device Model

android

### flutter info

```sh
flutter 3.16
```

### How to reproduce?

decodercallback is deperacted in image_provider of photo_manager2.8.1 

image_provider.dart should be changed:
DecoderCallback -> ImageDecoderCallback 

### Logs

```sh
photo_manager-2.8.1/lib/src/internal/image_provider.dart:71:5: Error: Type 'DecoderCallback' not found.
    DecoderCallback decode, // ignore: deprecated_member_use
```

### Example code (optional)

```Dart
Future<ui.Codec> _loadAsync(
    AssetEntityImageProvider key,
    DecoderCallback decode, // ignore: deprecated_member_use
  ) {
```

### Contact

planndocold@gmail.com

**Comment by AlexV525** [comment] 2023-11-21 15:15
Duplicate of #1021

**Closed by AlexV525** 2023-11-21 15:15 UTC
Labels: await triage
