### ISSUE TITLE
[Bug report] PlatformException(Asset file cannot be obtained., null, null, null) - Trying to read file in background task iOS

### ISSUE THREAD

**Issue by alextran1502** [fluttercandies/flutter_photo_manager#987] opened 2023-09-09 08:39 UTC
### Version

2.5.0

### Platforms

iOS

### Device Model

iPhone 12 Pro

### flutter info

```sh
0] % flutter doctor -v       
[✓] Flutter (Channel stable, 3.13.3, on macOS 13.4.1 22F770820d darwin-arm64, locale en-US)
    • Flutter version 3.13.3 on channel stable at /Users/alex/Documents/toolchain/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (2 days ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/alex/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Users/alex/Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/alex/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.82.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • Alex (mobile)   • 00008101-0003690E2183001E • ios            • iOS 16.6.1 20G81
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 116.0.5845.179

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### How to reproduce?

Hello, the API to get the originFile works fine when the app is in foreground, however I ran into an issue when executing a background task on iOS. Below is the relevant code

https://github.com/immich-app/immich/blob/f1db25762878d05a36d497c7d7dc742b3baeeef5/mobile/lib/modules/backup/services/backup.service.dart#L223-L227

I have made sure to register the plugin in the [AppDelegate](https://github.com/immich-app/immich/blob/f1db25762878d05a36d497c7d7dc742b3baeeef5/mobile/ios/Runner/AppDelegate.swift)

If you have any pointers, please let me know and thank you for a wonderful library!

### Logs

```sh
2023-09-09 15:04:03.213938+0700 Runner[10475:397873] flutter: ERROR backupAsset: PlatformException(Asset file cannot be obtained., null, null, null)
2023-09-09 15:04:03.215572+0700 Runner[10475:397873] flutter: ERROR backupAsset: PlatformException(Asset file cannot be obtained., null, null, null)
2023-09-09 15:04:03.217207+0700 Runner[10475:397873] flutter: ERROR backupAsset: PlatformException(Asset file cannot be obtained., null, null, null)
2023-09-09 15:04:03.219866+0700 Runner[10475:397873] flutter: ERROR backupAsset: PlatformException(Asset file cannot be obtained., null, null, null)
2023-09-09 15:04:03.222835+0700 Runner[10475:397873] flutter: ERROR backupAsset: PlatformException(Asset file cannot be obtained., null, null, null)
2023-09-09 15:04:03.225112+0700 Runner[10475:397873] flutter: ERROR backupAsset: PlatformException(Asset file cannot be obtained., null, null, null)
2023-09-09 15:04:03.227438+0700 Runner[10475:397873] flutter: ERROR backupAsset: PlatformException(Asset file cannot be obtained., null, null, null)
```

### Example code (optional)

```Dart
https://github.com/immich-app/immich/blob/f1db25762878d05a36d497c7d7dc742b3baeeef5/mobile/lib/modules/backup/services/backup.service.dart#L223-L227
```

### Contact

https://github.com/immich-app/immich

**Comment by utkarsh1097** [comment] 2023-09-14 19:00
We started seeing these logs after upgrading from version 2.6.0 to 2.7.1 ("latest"). However, reverting back to 2.6.0 resolved the issue since it didn't occur in that version.

**Comment by AlexV525** [comment] 2023-09-19 06:21
Could anyone do `git biesct` to determine which commit is the root cause? This would help us in resolving the issue a lot.

**Comment by CaiJingLong** [comment] 2023-09-19 07:52
Can you provide a simple code that can reproduce it stably?
It should be simple enough or just one button.

**Comment by alextran1502** [comment] 2023-09-25 04:26
I found a fix for this on iOS, I have to add `await PhotoManager.requestPermissionExtend();` before reading the file in the background context for it to work.

I am not sure why I didn't have to invoke this method before, but I have to do this now. The app has all permission granted on the foreground context anyway.

**Comment by AlexV525** [comment] 2023-09-30 07:41
Some methods will implicitly call for permissons, and now they are not.

**Closed by AlexV525** 2023-09-30 07:41 UTC
Labels: Sort: BUG, Platform: iOS, await investigate

**Comment by MayueCastbox** [comment] 2023-11-05 12:34
> I found a fix for this on iOS, I have to add `await PhotoManager.requestPermissionExtend();` before reading the file in the background context for it to work.
> 
> I am not sure why I didn't have to invoke this method before, but I have to do this now. The app has all permission granted on the foreground context anyway.

that save my life
