### ISSUE TITLE
Get AssetEntity by local paths

### ISSUE THREAD

**Issue by rbarzel** [fluttercandies/flutter_photo_manager#1087] opened 2024-02-19 14:43 UTC
### Platforms

Android, iOS

### Description

I want a new method that will accept a file path for a local image and return the corresponding `AssetEntity` or `AssetEntity.id`.

### Why

I want to be able to support [receive-sharing-intent](https://pub.dev/packages/receive_sharing_intent), which sends the app local file paths (for images in my situation). My app uploads photos to cloud based albums, and I need `AssetEntity.id` to prevent duplicate uploads.

**Comment by AlexV525** [comment] 2024-02-19 16:56
Duplicate of https://github.com/fluttercandies/flutter_photo_manager/issues/795

**Closed by AlexV525** 2024-02-19 16:56 UTC
Labels: await triage
