### ISSUE TITLE
[Bug report] Can't build android app bundle

### ISSUE THREAD

**Issue by jenniferdinh1997** [fluttercandies/flutter_photo_manager#1233] opened 2024-11-27 04:37 UTC
### Version

3.6.3

### Platforms

Android

### Device Model

All

### flutter info

```sh
[✓] Flutter (Channel stable, 3.24.5, on macOS 14.6.1 23G93 darwin-arm64, locale
    en-US)
    • Flutter version 3.24.5 on channel stable at
      /Users/jenniferdinh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (13 days ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/jenniferdinh/android
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/jenniferdinh/android
    • Java binary at: /usr/bin/java
    • Java version Java(TM) SE Runtime Environment (build 23+37-2369)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/macos-android-setup for detailed
      instructions).

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (4 available)
    • iPhone 16 (mobile)              • 6A3E2946-E0DD-4878-98BE-4BEE2FE987C7 •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-0 (simulator)
    • macOS (desktop)                 • macos                                •
      darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                •
      darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                               •
      web-javascript • Google Chrome 131.0.6778.86

[✓] Network resources
    • All expected network resources are available.
```

### How to reproduce?

running command "flutter build appbundle" to create a release for play store

### Logs

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':photo_manager:compileReleaseKotlin'.
> Error while evaluating property 'compilerOptions.jvmTarget' of task ':photo_manager:compileReleaseKotlin'.
   > Failed to calculate the value of property 'jvmTarget'.
      > Unknown Kotlin JVM target: 23

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

**Comment by fluttercandies-dev** [comment] 2024-11-27 04:40
**AI Summary:** The user is unable to build an Android App Bundle using `flutter build appbundle` with `photo_manager` version 3.6.3. They provided their `flutter info` output but no logs or example code.

**Comment by jenniferdinh1997** [comment] 2024-12-04 00:51
Hello, is there an update on this or any additional information you need from me? This is delaying an Android build for our app

**Comment by AlexV525** [comment] 2024-12-04 00:52
Duplicate of https://github.com/fluttercandies/flutter_photo_manager/issues/1198

**Closed by AlexV525** 2024-12-04 00:52 UTC
Labels: Sort: BUG, Platform: Android, Invalid: Missing requirements, await triage, Automation: triage
