### ISSUE TITLE
[Bug report] Compilation error under Flutter 3.16

### ISSUE THREAD

**Issue by koldoon** [fluttercandies/flutter_photo_manager#1042] opened 2023-11-20 16:42 UTC
### Version

2.8.1

### Platforms

dart

### Device Model

ios 14

### flutter info

```sh
Flutter 3.16.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision db7ef5bf9f (5 days ago) • 2023-11-15 11:25:44 -0800
Engine • revision 74d16627b9
Tools • Dart 3.2.0 • DevTools 2.28.2
```

### How to reproduce?

Upgrade flutter to latest version, use plugin as usual

### Logs

```sh
../../../../.pub-cache/hosted/pub.dev/photo_manager-2.8.1/lib/src/internal/image_provider.dart:71:5: Error: Type 'DecoderCallback' not found.
    DecoderCallback decode, // ignore: deprecated_member_use
    ^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/photo_manager-2.8.1/lib/src/internal/image_provider.dart:96:5: Error: Type 'DecoderCallback' not found.
    DecoderCallback decode, // ignore: deprecated_member_use
    ^^^^^^^^^^^^^^^
```

**Comment by AlexV525** [comment] 2023-11-20 16:53
Duplicate of #1021

**Closed by AlexV525** 2023-11-20 16:53 UTC
Labels: await triage
