### ISSUE TITLE
photo_manager-2.8.1/lib/src/internal/image_provider.dart:7 1:5: Error: Type 'DecoderCallback' not found.

### ISSUE THREAD

**Issue by lucasjinreal** [fluttercandies/flutter_photo_manager#1039] opened 2023-11-19 01:58 UTC
### Platforms

dart

### Description

photo_manager-2.8.1/lib/src/internal/image_provider.dart:7
1:5: Error: Type 'DecoderCallback' not found.

### Why

photo_manager-2.8.1/lib/src/internal/image_provider.dart:7
1:5: Error: Type 'DecoderCallback' not found.

**Comment by shinesincere** [comment] 2023-11-19 02:49
I'm also getting this error with Flutter 3.16.0 and Dart 3.2.0

**Comment by AlexV525** [comment] 2023-11-19 03:31
Duplicate of #1021

**Closed by AlexV525** 2023-11-19 03:31 UTC
Labels: await triage
