### ISSUE TITLE
[BUG] Some of the videos not showing in picker

### ISSUE THREAD

**Issue by NaikSoftware** [fluttercandies/flutter_photo_manager#646] opened 2021-11-17 18:40 UTC
**Describe the bug**
I use this library for a long time for images, but recently I tried to enable videos and some of users reported that cant see some videos, but can see in other apps like Facebook that also use MediaStore.

**How to reproduce**
Enable `common` or `videos` filter and open picker.

**Version information**

- Device: Realme 3 Pro and maybe some others
- OS: Android 10
- Package Version: 6.2.3
- Flutter Version: v2.5.3

**Additional context**
All not displayed videos are screencasts recorded by built in firmware recorder. When user sends "broken" video to any place (original without modification) and download on device again - it displayed.  So the file is valid. Especially since all native apps show this file sucessfully.
Can somehow suggest where to search the error? Maybe additional filters in picker or filters in underlying media manager (MediaStore), or consumed crash when getting preview can cause this.

**Comment by AlexV525** [comment] 2021-11-18 12:53
You can set debuggers at lines that return all entities queried from MediaStore, such as:
https://github.com/fluttercandies/flutter_photo_manager/blob/2ffa0b70926988570520711c3e0292a292041763/android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManager.kt#L81
And see the info of those videos.

**Comment by AlexV525** [comment] 2021-11-18 12:55
For what I concerning, those videos might have invalid width/height/duration, and a re-download retrieved the info when they're being stored again into MediaStore.

**Comment by NaikSoftware** [comment] 2021-12-14 00:07
Sorry, I haven't opportunity to debug user's phone:( I will fix issue if bug is reproduced in my devices.

**Comment by wuyugege** [comment] 2022-01-01 03:09
same question, on oppo phone, video produced by record the screen  will not show in the photo  library, but after  you rename the video ,it will show

**Comment by AlexV525** [comment] 2022-01-01 03:28
Seems it's most related to the screen recorder, and the mediastore entry has not been inserted once the recorder done recording.

**Comment by wuyugege** [comment] 2022-01-01 04:01
> 
can it be solved?  if i use other library ,like _images_picker_ ,there is no this question.
except this kind of video, some gif files cannot show either

**Comment by AlexV525** [comment] 2022-01-01 04:10
Can you try to debug with native Android, then put the debugger at where the resolver queried assets?

Images filtering could be resolved by `ignoreSize`.

**Comment by wuyugege** [comment] 2022-01-01 04:18
> Can you try to debug with native Android, then put the debugger at where the resolver queried assets?
i cannot understand what do yo mean

**Comment by AlexV525** [comment] 2022-01-01 04:23
Nevermind. Which OPPO device you've tested?

**Comment by wuyugege** [comment] 2022-01-01 04:33
i tested with oppo  a55 5g，i also tested with a hornor 9, there is no this question . i have a gif app, some of my oppo phone users also feedback this question, so i think oppo phone may be special

**Comment by AlexV525** [comment] 2022-01-02 09:48
I do confirm that some videos, especially videos created by screen recorders, are not able to be found with the current queries targeting the `MediaStore`. Though I'm not sure the root cause, I managed to exclude some conditions:

- Not related to `duration`
- Not related to `MediaColumn.BUCKET_ID`

**Comment by wuyugege** [comment] 2022-01-03 04:09
it means that this question cannot be solved temporarily?
the package _images_picker_ has no this question, may it can give you some idea

**Comment by dev-zhang** [comment] 2022-01-14 07:01
Hi, I encountered the same problem. 
When I downloaded some videos from "Xiaohongshu"（小红书） APP to test my app, I can't select them via wechat_assets_picker 6.3.1, the iOS version works fine, the Android version doesn't.
What I did:
1. I found that the video downloaded from "Xiaohongshu"（小红书） APP cannot display the correct duration in the system album of the phone
2. I downloaded the codes of wechat_assets_picker 6.3.1 and photo_manager 1.3.10 and tested them respectively, then the same problem appeared, these videos still did not appear
3. After I make some edits to these videos in the system album, such as adjusting their volume, their duration is displayed normally in the system album, and they can be displayed in wechat_assets_picker
4. In order to troubleshoot the problem, I made some changes to the code of photo_manager, when I changed the query code to 
```bucket_id IS NOT NULL AND ( ( media_type = ? ) OR ( media_type = ? AND duration IS NULL ) ) AND ( date_added > = ? AND date_added <= ? )```
 or 
```bucket_id IS NOT NULL AND ( ( media_type = ? ) ) AND ( date_added >= ? AND date_added <= ? )``` 
, these videos appeared
![](https://raw.githubusercontent.com/dev-zhang/imgHosting/master/img/WX20220114-144842%402x.png)
Hope these can help you solve these problems.
thanks.

**Comment by AlexV525** [comment] 2022-01-14 09:31
> 4. In order to troubleshoot the problem, I made some changes to the code of photo_manager, when I changed the query code to
>    `bucket_id IS NOT NULL AND ( ( media_type = ? ) OR ( media_type = ? AND duration IS NULL ) ) AND ( date_added > = ? AND date_added <= ? )`
>    or
>    `bucket_id IS NOT NULL AND ( ( media_type = ? ) ) AND ( date_added >= ? AND date_added <= ? )`
>    , these videos appeared

This clue helps a lot. Applying fix now.

**Closed** 2022-01-18 11:18 UTC
Labels: Sort: BUG, Type: Help wanted, Platform: Android, Type: Video, Status: Have use case

**Comment by wuyugege** [comment] 2022-03-03 05:24
i use ^2.0.0-dev.14 now ,but this problem still exist, video produced by record the screen not show in the photo library @AlexV525

**Comment by AlexV525** [comment] 2022-03-03 05:28
See #681 for how to obtain nullable duration videos.

**Comment by wuyugege** [comment] 2022-03-03 05:37
you mean: set _DurationConstraint(allowNullable: true)_ for durationConstraint of videoOption, when i call _PhotoManager.getAssetPathList_? @AlexV525 ,

**Comment by wuyugege** [comment] 2022-03-08 08:54
set _allowNullable_ to true is no use , video produced by record the screen still not show in the photo library @AlexV525

**Comment by AlexV525** [comment] 2022-03-08 10:29
> set _allowNullable_ to true is no use , video produced by record the screen still not show in the photo library @AlexV525

You might need to follow the same path as https://github.com/fluttercandies/flutter_photo_manager/issues/646#issuecomment-1012830426 suggested, to debug which condition can videos display.

**Comment by wuyugege** [comment] 2022-03-09 02:50
> 

i dont have ability to revise the code of plugin to debug , but if i rename the video ,it will show in photo library.
my device is oppo a55, if you dont have oppo phone , _https://open.oppomobile.com/cloudmachine/device/list-plus_ ,this website maybe help.

**Comment by AlexV525** [comment] 2022-03-09 02:52
> but if i rename the video ,it will show in photo library

If it does, this is typically a `MediaStore` bug, rather than this plugin.

**Comment by wuyugege** [comment] 2022-03-09 03:01
but if i use _image_picker_ , there is no problem, @AlexV525
