### ISSUE TITLE
[Bug report] 

### ISSUE THREAD

**Issue by Arbimig** [fluttercandies/flutter_photo_manager#926] opened 2023-04-18 04:40 UTC
### Version

2.6.0

### Platforms

Android

### Device Model

One plus 8(Android 13)

### flutter info

```sh
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale ru-RU)
    • Flutter version 3.0.5 at /Users/ibragim/develop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (9 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/ibragim/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (4 available)
    • IN2013 (mobile)            • 45e32a86                             • android-arm64  • Android 13 (API 33)
    • iPhone 13 Pro Max (mobile) • E5791C61-ABD4-4986-8D0C-7ED6E081CE8F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 112.0.5615.49

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

### How to reproduce?

On android we call the PhotoManager.getAssetPathList method as a result we get an empty list of albums, also with PhotoManager.getAssetCount() returns 0

### Logs

```sh
[log] getAssetPathList: []
[log] getAssetCount: 0
```

### Example code (optional)

```Dart
void getPhoto() async {
    final PermissionState _ps = await PhotoManager.requestPermissionExtend();
    if (_ps.isAuth) {
      int count = await PhotoManager.getAssetCount();

      final List<AssetPathEntity> paths = await PhotoManager.getAssetPathList();
      log('getAssetPathList: $paths');
      log('getAssetCount: $count');


      if (paths.isNotEmpty) {}
    } else {
      PhotoManager.openSetting();
      // Limited(iOS) or Rejected, use `==` for more precise judgements.
      // You can call `` to open settings for further steps.
    }
  }
```

**Comment by AlexV525** [comment] 2023-04-18 04:44
Duplicate of #852

**Closed by AlexV525** 2023-04-18 04:44 UTC
